 <?php $this->assets->outputCss() ?>
 <?php $this->assets->outputJs() ?>	

<div class="container">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <h3>Crear Nuevo Expediente de Paciente</h3>
			<form method="post">
            	<div class="form-group">
                	<label for="nombre" class="required">Nombre del Paciente</label>
                	<input type="text" name="nombre" class="form-control" placeholder="Nombre...">  
            	</div>
            	<div class="form-group ">
                	<label for="telefono" class="required">Telefono</label>
                	<input type="text"  name="telefono" class="form-control" placeholder="Telefono...">    
            	</div>
            	<div class="form-group">
                	<label for="direccion" class="required">Dirección</label>
                	<input type="text"  name="direccion" class="form-control" placeholder="Direccion...">    
            	</div>
            	<div class="form-group">
                	<label for="fechaNacimiento" class="required">Fecha de Nacimiento</label>
                	<input type="date"  name="fechaNacimiento" class="form-control" required="" placeholder="yyyy/mm/dd">    
            	</div>
            	<div class="form-group">
                	<label for="tipoSangre" class="required">Tipo de Sangre</label>
                	<div>
                    	<select class="custom-select" name="tipoSangre" id="tipoSangre">
                    	<option selected value="" >Seleccione una opcion</option>
                    	<option value="OPositivo">O positivo</option> 
                    	<option value="ONegatigo">O negativo</option>
                    	<option value="Negatigo">Negativo</option>
                    	</select>
                	</div>       
            	</div>
            	<div class="form-group">
                	<label for="sexo" class="required">Sexo</label>
                	<div>
                    	<select class="custom-select" name="sexo">
                    	<option selected value="" >Seleccione una opcion</option>
                    	<option value="Femenino">Femenino</option> 
                    	<option value="Masculino">Masculino</option>
                    	</select> 
                	</div>   
            	</div>
            	<div class="form-group">
                	<label for="estadoCivil" class="required">Estado Civil</label>
                	<div>
                    	<select class="custom-select" name="estadoCivil" >
	                    <option selected value="" >Seleccione una opcion</option>
	                    <option value="soltero">Soltero/a</option> 
	                    <option value="casado">Casado/a</option>
	                    <option value="acompanado">Acompanado/a</option>
	                    <option value="viudo">Viudo/a</option>
	                    <option value="divorsiado">Divorsiado/a</option>
                		</select>  
                	</div> 
            	</div>

            	<div class="form-group">
	                <button class="btn btn-primary" type="submit">Guardar</button>
	                <button class="btn btn-danger" type="reset">Cancelar</button>
            	</div>
         		
			</form>
		</div>
	</div>
</div>

